In [1]:
import numpy as np
import pandas as pd

In [3]:
data = [pd.read_csv('regions_pl_uro_{}_00_2p.csv'.format(year)) for year in range(2002, 2017)]

In [5]:
data[0]

,Unnamed: 0,region,total,1,2,3,4,5,6,7,8,9,10 i dalsze,nieustalona
0,4,DOLNOŚLĄSKIE,24588.0,12684.0,7543.0,2620.0,904.0,418.0,198,113,48,26,34,-
1,41,KUJAWSKO-POMORSKIE,20238.0,10074.0,6132.0,2253.0,887.0,453.0,196,108,65,28,40,2
2,71,LUBELSKIE,20908.0,9548.0,6437.0,2691.0,1134.0,512.0,275,148,81,42,37,3
3,102,LUBUSKIE,9486.0,4730.0,2926.0,1016.0,427.0,193.0,85,43,37,14,15,-
4,123,ŁÓDZKIE,22258.0,11419.0,7113.0,2325.0,787.0,316.0,160,59,34,16,25,4
5,154,MAŁOPOLSKIE,32451.0,14710.0,10254.0,4194.0,1723.0,773.0,360,189,121,52,72,3
6,183,MAZOWIECKIE,46627.0,23028.0,14821.0,5201.0,1979.0,848.0,362,186,90,67,44,1
7,232,OPOLSKIE,8506.0,3938.0,2704.0,1043.0,459.0,178.0,70,50,29,13,22,-
8,251,PODKARPACKIE,21414.0,9488.0,6592.0,2856.0,1239.0,616.0,297,151,82,40,53,-
9,283,PODLASKIE,11318.0,5032.0,3526.0,1528.0,646.0,290.0,141,64,35,26,29,1
10,307,POMORSKIE,22402.0,10758.0,6794.0,2635.0,1107.0,514.0,265,147,79,52,50,1
11,334,ŚLĄSKIE,39557.0,20291.0,12363.0,4162.0,1530.0,658.0,285,113,73,31,36,15
12,377,ŚWIĘTOKRZYSKIE,11837.0,5746.0,3683.0,1380.0,557.0,249.0,87,67,34,12,16,6
13,398,WARMIŃSKO-MAZURSKIE,14894.0,7015.0,4430.0,1764.0,815.0,406.0,196,113,63,40,51,1
14,426,WIELKOPOLSKIE,33253.0,16460.0,10358.0,3781.0,1384.0,605.0,333,155,85,37,49,6
15,468,ZACHODNIOPOMORSKIE,15789.0,7971.0,4674.0,1693.0,698.0,364.0,165,96,67,26,35,-